server:
  port: 8081
spring:
  datasource:
    url: jdbc:sqlserver://DURGASRAVANI;databaseName=Assists-u;trustServerCertificate=true
    username: sa
    password: Ask@6156
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
  application:
    name: didpatients